name: chatbackend

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build the application
        run: docker build -t chatbackend .

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Push to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/chatBackend
            git pull
            sudo docker build -t chatbackend .
            sudo docker stop chatbackend_container || true
            sudo docker rm chatbackend_container || true
            sudo docker run -d --name chatbackend_container chatbackend
