name: chatbackend

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build the application
        run: docker build -t chatbackend .

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          mkdir -p /home/runner/chatbackend/.ssh
          chmod 700 /home/runner/chatbackend/.ssh
          cd /home/runner/chatbackend/.ssh
          echo $PRIVATE_KEY > test
          chmod 640 test
          echo "Host $HOSTNAME" > config
          echo "  AddKeysToAgent yes" >> config
          echo "  ForwardAgent yes" >> config
          echo "  IdentityFile /home/runner/chatbackend/.ssh/test" >> config

      - name: Push to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.HOSTNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/chatBackend
            git pull
            docker build -t chatbackend . &&
            docker run -d --name chatbackend_container chatbackend
            exit
